version: '3.7'

services:
  emw:
    image: 'easy_manage_webserver'
    volumes:
      - static_volume:/staticfiles
    ports:
      - 8000:8000
    env_file:
      - ./emw/.env.emw
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./pg/.env.pg
  frontend_build:
    image: 'easy_manage_frontend:latest'
    volumes:
      - frontend_volume:/code
  nginx:
    image: 'easy_manage_nginx'
    volumes:
      - static_volume:/django/staticfiles
      - frontend_volume:/var/www/frontend
      - ./certs:/var/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - emw
      - frontend_build

volumes:
  postgres_data:
  static_volume:
  frontend_volume:
